name: Build release zip

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build plugin
        run: |
          composer install --no-dev
          cd vendor/threadi/easy-dialog-for-wordpress/
          npm install
          npm run build

      - name: ZIP plugin
        run: |
          zip -r -q ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*" "phpcs.xml" "composer.json" "composer.lock" ".gitignore" "vendor"
          zip -u -q ${{ github.event.repository.name }}.zip vendor/composer
          zip -u -q ${{ github.event.repository.name }}.zip vendor/threadi/easy-dialog-for-wordpress/build/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release.zip