name: Build release zip

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build plugin
        run: |
          composer install --no-dev
          cd vendor/threadi/easy-dialog-for-wordpress/
          npm install
          npm run build

      - name: ZIP plugin
        run: |
          cd ..
          zip -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}/* -x ".git/*" ".github/*" "phpcs.xml" "composer.json" "composer.lock" ".gitignore" "vendor/*"
          zip -u ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}/vendor/composer/*
          zip -u ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}/vendor/threadi/easy-dialog-for-wordpress/build/*

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release.zip