name: Build release zip

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build plugin
        run: |
          composer install --no-dev
          cd vendor/threadi/easy-dialog-for-wordpress/
          npm install
          npm run build

      - name: Generate zip
        uses: actions/create-release@v1
        with:
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false